name: ktv_mvp
description: "KTV MVP Website - Customer and Admin Portal"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.1  # For potential future API calls (optional for mocks)

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/data/
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf  # Assume default; add custom if needed
